import * as FS from 'expo-file-system/legacy';
import * as Picker from 'expo-image-picker';
import * as Manipulator from 'expo-image-manipulator';
import { requireOptionalNativeModule } from 'expo-modules-core';
import { isMealPhotoFile } from './meals';
import type { MealPhoto } from './mealPhotos';
export type { MealPhoto } from './mealPhotos';
const draftsRoot = `${FS.cacheDirectory}ebb-meal-drafts/`;
const native = requireOptionalNativeModule<{
  getStorageDirectory(kind: string): Promise<string>;
  statFile(uri: string): Promise<{ size: number; modifiedAt: number } | null>;
  copyFile(from: string, to: string): Promise<void>;
  removeFile(uri: string): Promise<void>;
  listDirectory(uri: string): Promise<string[]>;
}>('EbbLocalAi');
export const mealPhotosSupported = !!native;
async function photosRoot() {
  if (!native) throw new Error('This app build does not include local photo storage. Install the updated Ebb app.');
  const root = await native.getStorageDirectory('photos');
  return root.endsWith('/') ? root : `${root}/`;
}
export async function pickMealPhoto(source: 'camera' | 'library'): Promise<MealPhoto | null> {
  if (source === 'camera') {
    const permission = await Picker.requestCameraPermissionsAsync();
    if (!permission.granted) throw new Error('Camera permission is off. Allow it in your phone’s settings, or choose an existing photo.');
  }
  const options: Picker.ImagePickerOptions = { mediaTypes: ['images'], allowsEditing: false, exif: false, quality: 1, base64: false };
  const result = source === 'camera' ? await Picker.launchCameraAsync(options) : await Picker.launchImageLibraryAsync(options);
  const asset = result.canceled ? undefined : result.assets?.[0];
  if (!asset) return null;
  // Decode and re-encode a private JPEG copy: never store a gallery URI or EXIF.
  const factor = Math.min(1, 1280 / Math.max(asset.width, asset.height));
  let image: { uri: string } | undefined;
  try {
  image = await Manipulator.manipulateAsync(asset.uri, [{ resize: { width: Math.max(1, Math.round(asset.width * factor)), height: Math.max(1, Math.round(asset.height * factor)) } }], { compress: 0.8, format: Manipulator.SaveFormat.JPEG, base64: false });
  const file = `meal-${Date.now()}-${Math.random().toString(36).slice(2, 12)}.jpg`;
  const uri = `${draftsRoot}${file}`;
  try {
    await FS.makeDirectoryAsync(draftsRoot, { intermediates: true });
    await FS.copyAsync({ from: image.uri, to: uri });
    const info = await FS.getInfoAsync(uri);
    if (!info.exists || info.isDirectory || info.size <= 0) throw new Error('Could not prepare this photo. Choose a different picture.');
    return { uri, file, bytes: info.size };
  } catch (error) {
    await FS.deleteAsync(uri, { idempotent: true }).catch(() => {});
    throw error;
  } finally {
    // Only delete the file generated by our image-manipulation operation.
    await FS.deleteAsync(image.uri, { idempotent: true }).catch(() => {});
  }
  } finally {
    // ImagePicker quality=1 exports a second full-size cache copy, which can
    // retain EXIF even with exif:false. Never delete a gallery/content URI.
    if (FS.cacheDirectory && asset.uri.startsWith(`${FS.cacheDirectory}ImagePicker/`)) {
      await FS.deleteAsync(asset.uri, { idempotent: true }).catch(() => {});
    }
  }
}
export async function retainMealPhoto(photo: MealPhoto) {
  if (!isMealPhotoFile(photo.file) || photo.uri !== `${draftsRoot}${photo.file}`) throw new Error('Invalid meal photo.');
  const root = await photosRoot();
  const destination = `${root}${photo.file}`;
  // Copy first; keep the working copy until the diary entry is durably saved.
  try {
  await native!.copyFile(photo.uri, destination);
  const info = await native!.statFile(destination);
  if (!info || info.size !== photo.bytes) {
    throw new Error('Could not save the photo. Try data only or free some storage.');
  }
  return photo.file;
  } catch (error) {
    await native!.removeFile(destination).catch(() => {});
    throw error;
  }
}
export async function discardMealPhoto(photo: MealPhoto) {
  if (isMealPhotoFile(photo.file) && photo.uri === `${draftsRoot}${photo.file}`) await FS.deleteAsync(photo.uri, { idempotent: true });
}
export async function deleteSavedMealPhoto(file: string) {
  if (!isMealPhotoFile(file)) return;
  await native!.removeFile(`${await photosRoot()}${file}`);
}
export async function savedMealPhotoURI(file: string): Promise<string | null> {
  if (!isMealPhotoFile(file)) return null;
  const uri = `${await photosRoot()}${file}`;
  const info = await native!.statFile(uri);
  return info ? uri : null;
}
export async function clearMealPhotos() {
  if (native) await native.removeFile(await photosRoot());
  await cleanMealPhotoDrafts();
}
export async function cleanMealPhotoDrafts() {
  await FS.deleteAsync(draftsRoot, { idempotent: true });
  // This app uses ImagePicker only for meals. Remove its own abandoned cache
  // copies after process death; originals in the user's gallery are untouched.
  if (FS.cacheDirectory) {
    await FS.deleteAsync(`${FS.cacheDirectory}ImagePicker/`, { idempotent: true });
    await FS.deleteAsync(`${FS.cacheDirectory}ImageManipulator/`, { idempotent: true });
  }
}

export async function pruneMealPhotos(referenced: string[]) {
  if (!native) return;
  const root = await photosRoot(), keep = new Set(referenced);
  for (const file of await native.listDirectory(root)) {
    if (isMealPhotoFile(file) && !keep.has(file)) await native.removeFile(`${root}${file}`);
  }
}
